[tool.poetry]
name = "naac"
version = "0.1.0"
description = "Privacy Preserving Survey Platform"
authors = ["Chandramouli Velicheti"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
